apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurevolume
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurevolume-csi
  volumeName: azurevolume
  resources:
    requests:
      storage: 10Gi